language: csharp
mono: none
dotnet: 2.1.300

notifications:
  email: false

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx

# branches to build
branches:
  only:
    - master

cache:
  directories:
  - $HOME/.walletwasabi/
  - $HOME/.nuget/packages

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then ulimit -S -n 4096; fi
  - sudo killall bitcoind

script:
  - travis_wait dotnet test WalletWasabi.Tests/WalletWasabi.Tests.csproj --filter Category=RunOnCi
