configuration:
  - Release

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

cache:
- '%USERPROFILE%\.nuget\packages -> **\*.csproj'
- '%APPDATA%\MagicalCryptoWallet'
- Tor

install:
  - if not exist Tor\tor.exe appveyor DownloadFile https://www.torproject.org/dist/torbrowser/7.5/tor-win32-0.3.2.9.zip
  - if not exist Tor\tor.exe 7z x tor-win32-0.3.2.9.zip
  - ps: $TorProcess = Start-Process tor\tor.exe -PassThru

before_build:
  - ps: Start-Sleep -s 5
  
build_script:
  - dotnet build

test_script:
  - cd MagicalCryptoWallet.Tests
  - dotnet test

on_finish:
  - ps: Stop-Process -Id $TorProcess.Id
