configuration:
  - Release

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

cache:
- '%USERPROFILE%\.nuget\packages -> **\*.csproj'
- '%APPDATA%\WalletWasabi'

build_script:
  - tskill bitcoind # Make sure no hanging bticoind process is present.
  - cd WalletWasabi.Tests
  - dotnet build

test_script:
  - dotnet test --filter Category=RunOnCi

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))