trigger:
  batch: true
  branches:
    include:
      - master

pool:
  vmImage: windows-latest

steps:
- checkout: self
  path: WalletWasabi

- task: UseDotNet@2
  displayName: 'Install .NET'
  inputs:
    version: 8.0.x

- task: PowerShell@2
  displayName: 'Build and compare'
  inputs:
    targetType: 'inline'
    script: |
      # Change git output from stderr to stdout https://github.com/dahlbyk/posh-git/issues/109.
      $env:GIT_REDIRECT_STDERR = '2>&1'
      cd ..
      # Copy the source files to a different location and build from there.
      robocopy WalletWasabi WalletWasabiClone /COPYALL /S /NFL /NDL /NJH
      dotnet run --project WalletWasabi\WalletWasabi.Packager --onlybinaries
      dotnet run --project WalletWasabiClone\WalletWasabi.Packager --cdelivery

      Get-ChildItem -Recurse -Path WalletWasabiClone\WalletWasabi.Fluent.Desktop\bin\dist\cdelivery -Filter "*linux-x64.zip" | Expand-Archive -DestinationPath temp\linux-x64
      Get-ChildItem -Recurse -Path WalletWasabiClone\WalletWasabi.Fluent.Desktop\bin\dist\cdelivery -Filter "*macOS-x64.zip" | Expand-Archive -DestinationPath temp\osx-x64
      Get-ChildItem -Recurse -Path WalletWasabiClone\WalletWasabi.Fluent.Desktop\bin\dist\cdelivery -Filter "*macOS-arm64.zip" | Expand-Archive -DestinationPath temp\osx-arm64
      Get-ChildItem -Recurse -Path WalletWasabiClone\WalletWasabi.Fluent.Desktop\bin\dist\cdelivery -Filter "*win7-x64.zip" | Expand-Archive -DestinationPath temp\win7-x64

      git diff --no-index WalletWasabi\WalletWasabi.Fluent.Desktop\bin\dist temp
      if (0 -eq $LASTEXITCODE)
      {
          Write-Output "Deterministic build succeed"
      }
      else
      {
          Write-Output "Deterministic build failed"
      }
      exit $LASTEXITCODE
