blank_issues_enabled: false
contact_links:
  - name: ğŸ“ƒ User documentation
    url: https://docs.wasabiwallet.io/
    about: Search for any information about Wasabi.
  - name: ğŸ’ª Community support
    url: https://github.com/zkSNACKs/WalletWasabi/discussions/categories/support
    about: Feel free to ask anything.
  - name: â“ Other issue?
    url: https://github.com/zkSNACKs/WalletWasabi/discussions/
    about: Search on the community forum.
